name: "Allure Deployer Action"
description: "Deploy Allure reports with History, Retries, Aggregation and Slack integration"
author: "Sokari Gillis-Harry"

branding:
  icon: bar-chart
  color: green

runs:
  using: 'node20'
  main: "dist/index.js"
  post: "dist/utilities/cleanup.js"

inputs:
  google_credentials_json:
    description: "Set Firebase (Google Cloud) credentials for History, Retries and Firebase Hosting"
    required: false
  gcs_bucket:
    description: "Google Cloud/Firebase storage bucket to backup Allure History and Retries"
    required: false
  gcs_bucket_prefix:
    description: "Google Cloud/Firebase storage bucket path prefix to back up Allure results and history"
    required: false
  report_name:
    description: "Title of your report"
    default: "Allure Report"
  target:
    description: "Deployment target: firebase or github"
    required: true
  slack_channel:
    description: "Slack channel ID for notifications (optional)"
    required: false
  slack_token:
    description: "Slack Token"
    required: false
  allure_results_path:
    description: "A path/to/results or comma separate paths (path/to/results1,path/to/results2) of Allure results."
    required: true
  retries:
    description: "Number of previous test runs to show as retries in new test report (Default 0)"
    default: '0'
  show_history:
    description: "Show history in the test report (true/false)"
    default: "true"
  pr_comment:
    description: "Post test report information as pull request comment. Requires `github_token` to be set with permission  "
    default: "true"
  output:
    description: "A custom directory to generate Allure report into."
    required: false
  github_token:
    description: "Generated GITHUB_TOKEN or Personal Access Token for deploying report to GitHub pages and pr_comment"
    default: '${{ github.token }}'
  github_pages_branch:
    description: "Target branch for Deploying to GitHub Pages. Default: gh-pages"
    default: 'gh-pages'
  github_subfolder:
    description: "Git sub directory to write test report when hosting with GitHub Pages"
    default: ${{ github.run_id }}
  language:
    description: "Allure report language"
    default: 'en'
outputs:
  report_url:
    description: "URL to your test report"
