name: "Allure Deployer Action"
description: "Host your Allure Reports on the web, with history, retries, and Slack integration, No server required"
author: "Sokari Gillis-Harry"

branding:
  icon: bar-chart
  color: green

runs:
  using: "docker"
  image: "Dockerfile"

inputs:
  google_credentials_json:
    description: "Firebase (Google Cloud) credentials JSON"
    required: true
  storage_bucket:
    description: "A Google Cloud Storage bucket for managing Allure History and Retries"
    required: false
  report_name:
    description: "Name/Title of your report"
    default: "Allure Report"
  target:
    description: "Set where to deploy test Report. firebase or github"
    default: 'firebase'
  slack_channel:
    description: "Slack channel ID for notifications (optional)"
    required: false
  slack_token:
    description: "Slack Token"
    required: false
  allure_results_path:
    description: "Path to the directory containing Allure results"
    required: true
  retries:
    description: "Number of previous test runs to show as retries in new test report (Default 0)"
    default: '0'
  show_history:
    description: "Show history in the test report (true/false)"
    default: "true"
  prefix:
    description: "The storage bucket path to back up Allure results and history files"
    required: false
  pr_comment:
    description: "Post test report information as pull request comment. Requires `github_token` to be set with permission  "
    default: "false"
  output:
    description: "A directory to generate Allure report into. Setting this value disables report hosting and Slack notification"
    required: false
  github_token:
    description: "Set generated GITHUB_TOKEN for adding report info to pr as comment and deploying report to GitHub pages"
    required: false
  github_pages_branch:
    description: "Set target branch for Deploying test report to GitHub Pages"
    default: 'gh-pages'

outputs:
  report_url:
    description: "URL to your test report"
