jobs:
  aggregate-allure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Run test in multi-module project
        run: # Run test and create multiple allure results directories
      - name: Deploy Reports
        uses: cybersokari/allure-deployer-action@v1.8.0
        with:
          target: 'firebase'
          allure_results_path: 'allure-results_1,allure-results_2,allure-results_3'
          google_credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          gcs_bucket: ${{vars.STORAGE_BUCKET}}
          show_history: 'true'
          retries: 5