name: Deploy
on:
  workflow_dispatch:
    inputs:
      cli_version:
        description: Version of the CLI to include in the Docker image
        required: true
jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          build-args: CLI_VERSION=${{inputs.cli_version}}
          tags: |
            sokari/allure-deployer-action:${{ github.sha }}
            sokari/allure-deployer-action:${{inputs.cli_version}}