name: Test Actions
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run'
        type: choice
        options:
          - gh-pages
          - firebase
        default: gh-pages
      retries:
        description: 'Number of test runs to show as retries in report'
        default: '10'
      show-history:
        description: 'Show history in report'
        type: boolean
        default: true
      report-name:
        description: 'Title of the report'
        default: 'Allure Report'
      report-lang:
        description: 'Allure report language'
        type: choice
        default: en
        options:
          - en
          - ru
          - fr
          - de

jobs:
  firebase:
    if: ${{ github.event.inputs.job == 'firebase' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Deploy Reports to Firebase with History and Retries
        uses: cybersokari/allure-deployer-action@v1.7.5
        with:
          target: 'firebase'
          google_credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          allure_results_path: 'allure-results'
          storage_bucket: ${{secrets.STORAGE_BUCKET}}
          slack_channel: ${{secrets.SLACK_CHANNEL}}
          slack_token: ${{secrets.SLACK_TOKEN}}
          show_history: ${{github.event.inputs.show-history}}
          retries: ${{github.event.inputs.retries}}
          gcp_bucket_prefix: '${{github.repository}}/examples-firebase'

  gh-pages:
    if: ${{ github.event.inputs.job == 'gh-pages' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Deploy Reports to GitHub pages with History and Retries
        uses: cybersokari/allure-deployer-action@v1.7.5
        with:
          target: 'github'
          allure_results_path: 'allure-results'
          show_history: ${{github.event.inputs.show-history}}
          retries: ${{github.event.inputs.retries}}
          github_subfolder: 'examples-gh-pages'