name: Test Actions
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Select the job to run'
        type: choice
        options:
          - test-action-gh-pages
          - test-action-firebase
        default: test-action-gh-pages
      retries:
        description: 'Number of test runs to show as retries in report'
        default: '10'
      show-history:
        description: 'Show keep history in report'
        type: boolean
        default: true
      report-name:
        description: 'Title of the report'
        default: 'Allure Report'

jobs:
  test-action-firebase:
    if: ${{ github.event.inputs.job == 'test-action-firebase' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Deploy Reports to Firebase with History and Retries
        uses: cybersokari/allure-deployer-action@v1.4.2
        with:
          target: 'firebase'
          google_credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          allure_results_path: 'assets/allure-results'
          storage_bucket: ${{secrets.STORAGE_BUCKET}}
          slack_channel: ${{secrets.SLACK_CHANNEL}}
          slack_token: ${{secrets.SLACK_TOKEN}}
          show_history: ${{github.event.inputs.show-history}}
          retries: ${{github.event.inputs.retries}}
          prefix: 'test-action-firebase'

  test-action-gh-pages:
    if: ${{ github.event.inputs.job == 'test-action-gh-pages' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Deploy Reports to GitHub pages with History and Retries
        uses: cybersokari/allure-deployer-action@v1.4.2
        with:
          target: 'github'
          google_credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          github_pages_branch: 'gh-pages'
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          allure_results_path: 'assets/allure-results'
          storage_bucket: ${{secrets.STORAGE_BUCKET}}
          show_history: ${{github.event.inputs.show-history}}
          retries: ${{github.event.inputs.retries}}
          prefix: 'test-action-gh-pages'