name: Test Local Action
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run'
        type: choice
        options:
          - gh-pages
          - firebase
          - gh-pages-no-backup
        default: firebase
      runner:
        description: Runner to use
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        default: ubuntu-latest
      retries:
        description: 'Number of test runs to show as retries in report'
        type: number
        default: 10
      show-history:
        description: 'Show keep history in report'
        type: boolean
        default: true
      report-name:
        description: 'Title of the report'
        default: 'Allure Report'
      report-lang:
        description: 'Allure report language'
        type: choice
        default: en
        options:
          - en
          - ru
          - fr
          - de
      subfolder:
        description: 'GitHub sub directory'
        default: 'local-action'
      gh-pages-branch:
        description: 'Branch to deploy Github pages'
        default: 'gh-pages'
jobs:
  firebase:
    if: ${{ github.event.inputs.job == 'firebase' }}
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Deploy Reports to Firebase with History and Retries
        uses: ./
        with:
          target: 'firebase'
          google_credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          allure_results_path: 'allure-results'
          gcs_bucket: ${{secrets.STORAGE_BUCKET}}
          slack_channel: ${{secrets.SLACK_CHANNEL}}
          slack_token: ${{secrets.SLACK_TOKEN}}
          show_history: ${{github.event.inputs.show-history}}
          retries: ${{github.event.inputs.retries}}
          gcs_bucket_prefix: 'test-action-firebase'
          report_name: ${{github.event.inputs.report-name}}
          language: ${{github.event.inputs.report-lang}}
          github_subfolder: ${{github.event.inputs.subfolder}}
  gh-pages:
    if: ${{ github.event.inputs.job == 'gh-pages' }}
    runs-on: ${{ github.event.inputs.runner }}
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Deploy Reports to GitHub pages with History and Retries
        uses: ./
        with:
          target: 'github'
          github_pages_branch: 'gh-pages'
          allure_results_path: 'allure-results'
          show_history: ${{github.event.inputs.show-history}}
          retries: ${{github.event.inputs.retries}}
          report_name: ${{github.event.inputs.report-name}}
          language: ${{github.event.inputs.report-lang}}
          github_subfolder: ${{github.event.inputs.subfolder}}

  gh-pages-no-backup:
    if: ${{ github.event.inputs.job == 'gh-pages-no-backup'}}
    runs-on: ${{ github.event.inputs.runner }}
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Deploy Reports to GitHub pages
        uses: ./
        with:
          target: 'github'
          github_pages_branch: ${{ github.event.inputs.gh-pages-branch }}
          allure_results_path: 'allure-results'
          report_name: ${{github.event.inputs.report-name}}
          language: ${{github.event.inputs.report-lang}}
          github_subfolder: ${{github.event.inputs.subfolder}}