name: Test GitHub locally
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run'
        type: choice
        options:
          - gh
          - gh-no-backup
          - gh-multi
        default: gh
      runner:
        description: Runner to use
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        default: ubuntu-latest
      retries:
        description: 'Number of test runs to show as retries in report'
        type: number
        default: 10
      show-history:
        description: 'Show keep history in report'
        type: boolean
        default: true
      report-name:
        description: 'Title of the report'
        default: 'Allure Report'
      report-lang:
        description: 'Allure report language'
        type: choice
        default: en
        options:
          - en
          - ru
          - fr
          - de
      prefix:
        description: 'Prefix'
        default: 'local-action'
      branch:
        description: 'GitHub pages deployment branch'
        default: 'gh-pages'
      slack:
        description: "Send slack message"
        type: boolean
        default: false
jobs:
  gh:
    if: ${{ github.event.inputs.job == 'gh' }}
    runs-on: ${{ github.event.inputs.runner }}
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Deploy Reports to GitHub pages with History and Retries
        uses: ./
        with:
          target: 'github'
          github_pages_branch: ${{github.event.inputs.branch}}
          gh_artifact_prefix: ${{github.event.inputs.prefix || ''}}
          allure_results_path: 'allure-results'
          show_history: ${{github.event.inputs.show-history}}
          retries: ${{github.event.inputs.retries}}
          report_name: ${{github.event.inputs.report-name}}
          language: ${{github.event.inputs.report-lang}}
          slack_channel: ${{github.event.inputs.slack == true && secrets.SLACK_CHANNEL || '' }}
          slack_token: ${{github.event.inputs.slack == true && secrets.SLACK_TOKEN || ''}}

  gh-multi:
    if: ${{ github.event.inputs.job == 'gh-multi' }}
    runs-on: ${{ github.event.inputs.runner }}
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Deploy Reports to GitHub pages 1
        uses: ./
        with:
          target: 'github'
          github_pages_branch: ${{github.event.inputs.branch}}
          gh_artifact_prefix: ${{github.event.inputs.prefix || ''}}
          allure_results_path: 'allure-results'
          show_history: ${{github.event.inputs.show-history}}
          retries: ${{github.event.inputs.retries}}
          report_name: ${{github.event.inputs.report-name}}
          language: ${{github.event.inputs.report-lang}}
          slack_channel: ${{github.event.inputs.slack == true && secrets.SLACK_CHANNEL || '' }}
          slack_token: ${{github.event.inputs.slack == true && secrets.SLACK_TOKEN || ''}}

      - name: Deploy Reports to GitHub pages 2
        uses: ./
        with:
          target: 'github'
          github_pages_branch: ${{github.event.inputs.branch}}
          gh_artifact_prefix: ${{github.event.inputs.prefix || ''}}
          allure_results_path: 'allure-results'
          show_history: ${{github.event.inputs.show-history}}
          retries: ${{github.event.inputs.retries}}
          report_name: ${{github.event.inputs.report-name}}
          language: ${{github.event.inputs.report-lang}}
          slack_channel: ${{github.event.inputs.slack == true && secrets.SLACK_CHANNEL || '' }}
          slack_token: ${{github.event.inputs.slack == true && secrets.SLACK_TOKEN || ''}}

  gh-no-backup:
    if: ${{ github.event.inputs.job == 'gh-no-backup'}}
    runs-on: ${{ github.event.inputs.runner }}
    permissions:
      contents: write
      actions: none
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Deploy Reports to GitHub pages
        uses: ./
        with:
          target: 'github'
          github_pages_branch: ${{github.event.inputs.branch}}
          allure_results_path: 'allure-results'
          show_history: ${{github.event.inputs.show-history}}
          retries: ${{github.event.inputs.retries}}
          report_name: ${{github.event.inputs.report-name}}
          language: ${{github.event.inputs.report-lang}}
          slack_channel: ${{github.event.inputs.slack == true && secrets.SLACK_CHANNEL || '' }}
          slack_token: ${{github.event.inputs.slack == true && secrets.SLACK_TOKEN || ''}}